"""empty message

Revision ID: 0e53bc3822bb
Revises: aafc86df9a62
Create Date: 2021-12-13 22:27:06.540092

"""

# revision identifiers, used by Alembic.
revision = '0e53bc3822bb'
down_revision = 'aafc86df9a62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
