"""empty message

Revision ID: 16cd409fce7a
Revises: dc1eee44d2c6
Create Date: 2021-12-14 12:51:33.950732

"""

# revision identifiers, used by Alembic.
revision = '16cd409fce7a'
down_revision = 'dc1eee44d2c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
