"""empty message

Revision ID: 6b51368baa2d
Revises: 823d1ca0f522
Create Date: 2021-12-14 11:53:11.919126

"""

# revision identifiers, used by Alembic.
revision = '6b51368baa2d'
down_revision = '823d1ca0f522'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
