"""empty message

Revision ID: 76a5204f6360
Revises: 16cd409fce7a
Create Date: 2021-12-14 13:42:02.539406

"""

# revision identifiers, used by Alembic.
revision = '76a5204f6360'
down_revision = '16cd409fce7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
