"""empty message

Revision ID: 7a104dde7f06
Revises: fb239a487de4
Create Date: 2021-12-14 12:10:01.923293

"""

# revision identifiers, used by Alembic.
revision = '7a104dde7f06'
down_revision = 'fb239a487de4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
