"""empty message

Revision ID: 823d1ca0f522
Revises: f5b8017349a8
Create Date: 2021-12-14 11:52:51.767022

"""

# revision identifiers, used by Alembic.
revision = '823d1ca0f522'
down_revision = 'f5b8017349a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
