"""empty message

Revision ID: a6449c82749c
Revises: 76a5204f6360
Create Date: 2021-12-14 14:44:16.623804

"""

# revision identifiers, used by Alembic.
revision = 'a6449c82749c'
down_revision = '76a5204f6360'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
