"""empty message

Revision ID: aafc86df9a62
Revises: 4c9f007d4e9b
Create Date: 2021-12-13 21:57:38.094659

"""

# revision identifiers, used by Alembic.
revision = 'aafc86df9a62'
down_revision = '4c9f007d4e9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
