"""empty message

Revision ID: be1885786316
Revises: 6b51368baa2d
Create Date: 2021-12-14 11:57:46.365301

"""

# revision identifiers, used by Alembic.
revision = 'be1885786316'
down_revision = '6b51368baa2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
