"""empty message

Revision ID: ca2682ef3eff
Revises: 0e53bc3822bb
Create Date: 2021-12-14 09:48:15.165255

"""

# revision identifiers, used by Alembic.
revision = 'ca2682ef3eff'
down_revision = '0e53bc3822bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
