"""empty message

Revision ID: dc1eee44d2c6
Revises: be1885786316
Create Date: 2021-12-14 12:04:11.742591

"""

# revision identifiers, used by Alembic.
revision = 'dc1eee44d2c6'
down_revision = 'be1885786316'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
