"""empty message

Revision ID: f5b8017349a8
Revises: fb239a487de4
Create Date: 2021-12-14 11:51:04.460595

"""

# revision identifiers, used by Alembic.
revision = 'f5b8017349a8'
down_revision = 'fb239a487de4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
