"""empty message

Revision ID: fb239a487de4
Revises: ca2682ef3eff
Create Date: 2021-12-14 09:49:52.687669

"""

# revision identifiers, used by Alembic.
revision = 'fb239a487de4'
down_revision = 'ca2682ef3eff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
